"""empty message

Revision ID: 330527c0a4a5
Revises: 
Create Date: 2019-05-16 09:05:53.245368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330527c0a4a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ur_ls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('keyword', sa.String(length=400), nullable=True),
    sa.Column('source', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ur_ls')
    # ### end Alembic commands ###
